# Generated by Django 4.2.5 on 2024-06-29 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SuppierCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.itemcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra-Extra Large')], default='S', max_length=50)),
                ('catalogue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppiercatalogue')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.IntegerField(choices=[(0, 0), (1, 180), (2, 210), (3, 240), (4, 320)], default=0)),
                ('catalogue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppiercatalogue')),
            ],
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('NAN', 'none'), ('red', 'red')], default='none', max_length=10)),
                ('catalogue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppiercatalogue')),
            ],
        ),
    ]
