# Generated by Django 5.0.6 on 2024-06-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_addressdata_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address_id',
            new_name='address',
        ),
    ]
